Layr-Labs/eigenlayer-middleware

src/BLSRegistryCoordinatorWithIndices.sol
Function was unecessarily long because it was checking the same thing multiple times. This commit straightens shit out.
=> refactor: simplify _registerOperatorWithCoordinator

src/BLSRegistryCoordinatorWithIndices.sol, test/unit/BLSRegistryCoordinatorWithIndicesUnit.t.sol
also add a minimal regression test, which simply checks that re-registering is possible!
=> BUGFIX: make it possible for operators to reregister

src/BLSRegistryCoordinatorWithIndices.sol, src/StakeRegistry.sol, test/harnesses/StakeRegistryHarness.sol, test/unit/BLSSignatureCheckerUnit.t.sol, test/unit/StakeRegistryUnit.t.sol
This PR:
* changes for loop index names to things like "i" or "j" when the index is just an index. The wordy index names were bugging me.
* Refactors StakeRegsitry to use a signed delta in most places, which allows us to get rid of a lot of bloat
Functional changes in StakeRegistry:
* Total stake updates are only made if we have a nonzero stake delta. Otherwise we skip them.
* For both total and operator updates, if the most recent entry was made during this block, we update that entry rather than pushing a new one. This should mean that all histories only have one entry per block.
=> Refactor StakeRegistry to use a signed delta for stake updates

src/StakeRegistry.sol
The removed code made it possible for `updateStakes` to infinitely loop when processing an empty bitmap. Will open an issue to add a regression test.
=> fix: remove possible infinite loop when updating stakes

src/BLSSignatureChecker.sol, src/interfaces/IBLSSignatureChecker.sol
Reverting a change to return an address instead of the interface that I had made while troubleshooting the migration
=> fix: Revert blsPubkeyRegistry interface return type

src/BLSRegistryCoordinatorWithIndices.sol, src/IndexRegistry.sol, src/IndexRegistryStorage.sol, src/interfaces/IBLSRegistryCoordinatorWithIndices.sol, src/interfaces/IIndexRegistry.sol, test/unit/BLSOperatorStateRetrieverUnit.t.sol, test/unit/BLSRegistryCoordinatorWithIndicesUnit.t.sol, test/unit/IndexRegistryUnit.t.sol
Simplify index registry.
The aim to to get rid of the operators to swap param.
Some downsides: 
- operatorUpdate is now 2 storage slots
- new map for current operator index for quorums
However, the global operator list is removed, so that reduces a fair amount of storage
=> FEAT: update index reg and propagate changes. need to fix indexreg tests

src/BLSOperatorStateRetriever.sol, src/BLSPubkeyRegistry.sol, src/BLSRegistryCoordinatorWithIndices.sol, src/BLSSignatureChecker.sol, src/IndexRegistry.sol, src/IndexRegistryStorage.sol, src/StakeRegistry.sol, src/StakeRegistryStorage.sol, src/interfaces/IBLSRegistryCoordinatorWithIndices.sol, src/interfaces/IIndexRegistry.sol, src/interfaces/IRegistryCoordinator.sol, src/interfaces/IStakeRegistry.sol, test/harnesses/BLSRegistryCoordinatorWithIndicesHarness.sol, test/mocks/RegistryCoordinatorMock.sol, test/mocks/StakeRegistryMock.sol, test/unit/BLSOperatorStateRetrieverUnit.t.sol, test/unit/BLSPubkeyRegistryUnit.t.sol, test/unit/BLSRegistryCoordinatorWithIndicesUnit.t.sol, test/unit/BLSSignatureCheckerUnit.t.sol, test/unit/IndexRegistryUnit.t.sol, test/unit/StakeRegistryUnit.t.sol, test/unit/VoteWeigherBaseUnit.t.sol, test/utils/MockAVSDeployer.sol
Motivation:
* fix word soup variable and function naming
* take advantage of new quorum existence invariant due to `RegistryCoordinator.createQuorum` and its associated `initializeQuorum` methods in each registry
* registries each keep "histories" of updates. The status quo is that every time anything changes, we push a new history update. this means that when updates happen multiple times in the same block, the history contains multiple updates from the same block number, making it harder to determine what the canonical state at a given block number is.
This PR:
* Replaces logic that handles "0-length histories" with simple checks, since we now have an invariant that initialized quorums have nonzero histories (see any registry's `initializeQuorum` method)
* changes registry histories to …
=> refactor: simplify naming and logic in registries and registry coordinator

src/BLSOperatorStateRetriever.sol, src/BLSPubkeyRegistry.sol, src/BLSPubkeyRegistryStorage.sol, src/BLSPublicKeyCompendium.sol, src/BLSRegistryCoordinatorWithIndices.sol, src/BLSSignatureChecker.sol, src/interfaces/IBLSPubkeyRegistry.sol, src/interfaces/IBLSPublicKeyCompendium.sol, src/interfaces/IBLSRegistryCoordinatorWithIndices.sol, test/ffi/BLSPubKeyCompendiumFFI.t.sol, test/mocks/BLSPublicKeyCompendiumMock.sol, test/unit/BLSOperatorStateRetrieverUnit.t.sol, test/unit/BLSPubkeyRegistryUnit.t.sol, test/unit/BLSRegistryCoordinatorWithIndicesUnit.t.sol, test/unit/BLSSignatureCheckerUnit.t.sol, test/utils/MockAVSDeployer.sol
Builds on PR #28 and #43; merge those first! It looks like I'm merging 20 commits, but those are actually commits from the other PRs :) Only the final 2 commits in this PR are relevant.
Functional changes in this PR:
* adds a new mapping to `BLSPublicKeyCompendium` : `operatorToPubkey`, which maps operator addresses to `G1Point` 
* adds a method `BLSPublicKeyCompendium.getRegisteredPubkey(address)` which performs a pubkey lookup along with validation that the pubkey exists/isn't the zero pubkey. 
* Validation logic here was previously performed in the `BLSPubkeyRegistry`
* Removes the "pubkey" parameter from various functions, like in the `BLSPubkeyRegistry` and `BLSRegistryCoordinatorWithIndices`. The pubkey registry is able to look up pubkeys with just an operator address, now. …
=> refactor: pubkey compendium stores pubkeys

src/BLSRegistryCoordinatorWithIndices.sol
Needs a regression test; will open an issue.
=> fix: registry coordinator churn now uses correct kick index

src/BLSOperatorStateRetriever.sol, src/BLSPubkeyRegistry.sol, src/BLSPubkeyRegistryStorage.sol, src/BLSPublicKeyCompendium.sol, src/BLSRegistryCoordinatorWithIndices.sol, src/BLSSignatureChecker.sol, src/IndexRegistry.sol, src/ServiceManagerBase.sol, src/StakeRegistry.sol, src/interfaces/IBLSPubkeyRegistry.sol, src/interfaces/IBLSPublicKeyCompendium.sol, src/interfaces/IBLSRegistry.sol, src/interfaces/IBLSRegistryCoordinatorWithIndices.sol, src/interfaces/IBLSSignatureChecker.sol, src/libraries/BN254.sol, src/libraries/BitmapUtils.sol, test/ffi/BLSSignatureCheckerFFI.t.sol, test/ffi/util/G2Operations.sol, test/harnesses/BitmapUtilsWrapper.sol, test/mocks/BLSPublicKeyCompendiumMock.sol, test/unit/StakeRegistryUnit.t.sol, test/utils/BLSMockAVSDeployer.sol, test/utils/MockAVSDeployer.sol, test/utils/Operators.sol, test/utils/ProofParsing.sol
Moves these libraries to middleware, since they're only used here
Depends on first merging core PR: https://github.com/Layr-Labs/eigenlayer-contracts/pull/319
Once that's merged I'll push a final commit to update submodules, so please go review the above PR first!
Edit: Ready for merge!
=> chore: move BitmapUtils and BN254 libraries to middleware

src/BLSRegistryCoordinatorWithIndices.sol
Also makes use of the helper in the contract's other methods
=> refactor: remove quorumsAllExist modifier in favor of helper

src/BLSSignatureChecker.sol
fixes a bug where the first nonSignerStakeIndex is used for all non signers
=> update nonSignerForQuorumIndex outside of loop

.gitmodules
Updating commit from `bccae53` to `b91a743`
Latest m2-mainnet commits can be viewed here https://github.com/Layr-Labs/eigenlayer-contracts/commits/m2-mainnet
=> Build: Set lib/eigenlayer-contracts submodule to m2-mainnet branch

src/RegistryCoordinator.sol, src/interfaces/IIndexRegistry.sol, src/interfaces/IRegistryCoordinator.sol, src/interfaces/IStakeRegistry.sol, test/harnesses/RegistryCoordinatorHarness.sol, test/integration/CoreRegistration.t.sol, test/unit/RegistryCoordinatorUnit.t.sol, test/unit/StakeRegistryUnit.t.sol, test/utils/MockAVSDeployer.sol
This PR adds AVS<>Operator registration support in the RegistryCoordinator. It calls the core contract functions added in [this core PR.](https://github.com/Layr-Labs/eigenlayer-contracts/pull/363)
Removed kickIndex in the `registerOperatorWithChurn` function as it was an unused variable.
=> Feat: Add AVS/Operator Registration Support in RegistryCoordinator

src/BLSApkRegistry.sol, src/RegistryCoordinator.sol, src/interfaces/IBLSApkRegistry.sol, test/ffi/BLSPubKeyCompendiumFFI.t.sol, test/unit/BLSApkRegistryUnit.t.sol, test/unit/RegistryCoordinatorUnit.t.sol, test/utils/MockAVSDeployer.sol
Opening this is a "sub-PR" / add-on to https://github.com/Layr-Labs/eigenlayer-middleware/pull/97
Now that the pubkey compendium has been merged into other middleware contracts / is on a per-AVS basis, we can make the call to register a new pubkey permissioned + make a single function that combines what was previously 2 calls.
=> Feat: combined operator registration flow

src/BLSApkRegistry.sol, src/RegistryCoordinator.sol, src/interfaces/IBLSApkRegistry.sol, src/interfaces/IRegistryCoordinator.sol, test/ffi/BLSPubKeyCompendiumFFI.t.sol, test/mocks/RegistryCoordinatorMock.sol, test/unit/BLSApkRegistryUnit.t.sol
Aimed at addressing the last couple TODOs in https://github.com/Layr-Labs/eigenlayer-middleware/pull/97
I pulled these changes out into a separate PR because review has already been done on the existing changes in that PR / I think they are quite well-contained.
I initially thought I'd want to do more renaming, but I think the primary commit here -- https://github.com/Layr-Labs/eigenlayer-middleware/commit/630b27d394191b89d6c88e7a1b8dda07750a31db -- takes care of the worst offender, and I'm not strongly opinionated enough to fight for other naming changes right now.
=> Chore: cleanup for compendium changes

src/BLSApkRegistry.sol, src/BLSSignatureChecker.sol, src/RegistryCoordinator.sol, src/StakeRegistry.sol, src/libraries/BN254.sol, test/mocks/DelegationMock.sol, test/utils/MockAVSDeployer.sol
Fixes:
- swap sign on withdrawal delay check
- adjust withdrawal delay check so that it checks against `referenceBlockNumber` rather than `block.number`
- add fix for `BN254.scalar_mul_tiny` from #76 
Other changes:
- comments, clarity, and renaming
- adds input validation for all parameters
- cache state to avoid lookups in loop
- remove an uneeded loop from checkSignatures
- only negate pubkeys a single time, rather than each time a nonsigner pk is added
=> fix: address multiple issues in BLSSignatureChecker, optimize, and clean

src/ServiceManagerBase.sol, src/StakeRegistry.sol, src/interfaces/IServiceManager.sol, test/integration/CoreRegistration.t.sol, test/utils/MockAVSDeployer.sol
We need to index operators restaked on each AVS to support our user stories for [V1 AVS Marketplace](https://docs.google.com/document/d/17PStsH5qXFNWUzjzr-vyzASy_6bjMd_tuf234bkejkg/edit).
=> Feat: Add Operator Strategy Indexing to Service Manager

foundry.toml, src/RegistryCoordinator.sol, src/ServiceManagerBase.sol, src/StakeRegistry.sol, src/interfaces/IServiceManager.sol, test/harnesses/RegistryCoordinatorHarness.t.sol, test/integration/CoreRegistration.t.sol, test/unit/RegistryCoordinatorUnit.t.sol, test/unit/StakeRegistryUnit.t.sol, test/utils/MockAVSDeployer.sol
Reintroduce an IServiceManager interface and ServiceManagerBase, but including only on the very minimal interactions we are requiring from AVSs (the other one was very slashing-focused, so there really isn’t overlap between the old interface and this new one)
We clearly aren’t going to be able to jam that much more into the RegistryCoordinator, and setting EigenLayer up to have to worry about multiple AVS contracts is a recipe for headaches down the line.
We know we’ll be adding more interactions where AVSs push data to EigenLayer in the future, and it seems highly unlikely we can fit these into the RegistryCoordinator, or that these would be the right place even if we could.
I also feel like this is better separation of concerns. Hopefully AVS developers have less to worry about here — …
=> feat: concentrate eigenlayer avs interactions into service manager

README.md
I initially didn't understand "Registry Coordinator/Registry Architecture" in the doc as this phrasing appears to be symmetric of "Registry Coordinator" + "Registry Architecture"
after reading the doc, i realized it's actually "Architecture of Registry Coordinator and Registry"
so making a change to avoid confusing others
=> Update README.md to avoid confusing phrasing
